export const videoProjects = [
  {
    id: 1,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/a8f2rzz5v3v37wl68d3ck/FROSINONE_ROMA.mp4?rlkey=p28hvapygiuqpfwxyp6eib50w&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "ROMA",
  },
  {
    id: 2,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/20ywy2rqy11jg20mivevi/CALCUTTA_ROMA_01.mp4?rlkey=mq9d0rzya0sfv4r9rw5fsiggg&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "ROMA",
  },
  {
    id: 3,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/rwjio5i4hoactp9byaquz/GAETANO.mp4?rlkey=gi45va5o0cqchzgh79zow5gg6&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "ALBA",
  },
  {
    id: 4,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/k8hrfv6azrpx2hauaz6rq/LIMONATA.mp4?rlkey=o4as9kp4u9do8y5rvhrhdn2sd&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "ALBA",
  },
  {
    id: 5,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/jxubh31osjh2nwf6abmkg/PESTO_LUCCA_2.mp4?rlkey=9og2h9018fch3i0b1taj1m5n5&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "LUCCA",
  },
  {
    id: 6,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/fl4g2j9wtsfpkphk4xi2e/PESTO_LUCCA.mp4?rlkey=l1oxa28n6qgpe3gynl27vsk61&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "LUCCA",
  },
  {
    id: 7,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/gpub5zy2p5fpvlx1cz5vf/DUEMIN_LUCCA.mp4?rlkey=zjwbblphfj0oundhd5z0cttgc&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "LUCCA",
  },
  {
    id: 8,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/zksb4dw8w630plejiqp7v/DEL-VERDE.mp4?rlkey=sv2cp3ybqgf40nbo7ri91znv9&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "LUCCA",
  },
  {
    id: 9,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/ne2xvm88sxh18zaztzcdn/DUEMIN_VILLAFRANCA.mp4?rlkey=fqlkjie4z6tlmva8uutnthewo&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "VILLAFRANCA",
  },
  {
    id: 10,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/sl57xls1l0sfhlvxonldy/FROSINONE_VILLAFRANCA.mp4?rlkey=b5y5r7uwkjs2oqtajshqb1uq9&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "VILLAFRANCA",
  },
  {
    id: 11,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/2qcyin7pp1625ktg05pq3/ALLEGRIA_VILLAFRANCA.mp4?rlkey=xgyboeyjbd8ksba5vjudptywx&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "VILLAFRANCA",
  },
  {
    id: 12,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/pr54wdh0l4zip2b7vg1jn/PARACETAMOLO_VILLAFRANCA.mp4?rlkey=3o6nmysw7kuu1uvf54e1fsjsc&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "VILLAFRANCA",
  },
  {
    id: 13,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/zydq81yi6l7bvzt8xopxy/MILANO_GAETANO.mp4?rlkey=kbyi7mhxt3fu9j85xp6a3iw83&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "MILANO",
  },
  {
    id: 14,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/q0aky3ewqvp00a5iegdzo/MILANO_HUBNER.mp4?rlkey=1e3ebwb5s7cwkm93gf8kzmnyw&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "MILANO",
  },
  {
    id: 15,
    idProject: 20,
    url: "https://www.dropbox.com/scl/fi/s7s4kti2a6iol05az0r6l/SORRISO_PAESTUM.mp4?rlkey=qgpc5wi2vzyl6aivgw19n5lp1&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "PAESTUM",
  },
  {
    id: 16,
    idProject: 1,
    url: "https://www.dropbox.com/scl/fi/8isux09v6qzf07kiv140x/RVF24-DAY-1_16.9_Clean.mp4?rlkey=ctpywjtyzyfysvagzxxrsvew7&st=gmv1rf93&raw=1", // Day 1 link
    title: "RED VALLEY",
    subtitle: "DAY 1",
  },
  {
    id: 17,
    idProject: 1,
    url: "https://www.dropbox.com/scl/fi/o84dupkczesx71f9al68p/RVF24-DAY-2_16.9_Clean.mp4?rlkey=5ipbjroxs92lmsfzudz5keszh&st=vqelz1uo&raw=1", // Day 3 link
    title: "RED VALLEY",
    subtitle: "DAY 2",
  },
  {
    id: 18,
    idProject: 1,
    url: "https://www.dropbox.com/scl/fi/gqhg4t4a9uqryrxzq8an5/REEL-DAY-3-16_9.mp4?rlkey=vr8i2bcpef3hc4npl7gxm35sg&st=k0jkjkzo&raw=1", // Day 4 link
    title: "RED VALLEY",
    subtitle: "DAY 4",
  },
  {
    id: 19,
    idProject: 1,
    url: "https://www.dropbox.com/scl/fi/kv77ldvy3raz98bamlzcj/DEF-PRORES.mov?rlkey=55bhux05mumcq37zaxsm3hmv9&raw=1", // Dropbox video link
    title: "Special Project",
    subtitle: "DEF-PRORES",
  },
  {
    id: 20,
    idProject: 19,
    url: "https://www.dropbox.com/s/xxxxxx/IGS_D1_Mecna.mp4?raw=1",
    title: "",
    subtitle: "",
  },
  {
    id: 21,
    idProject: 12,
    url: "/images/fulminacci2.png",
    alt: "Fulminacci",
  },
  {
    id: 22,
    idProject: 12,
    url: "/images/fulminacci3.png",
    title: "",
    subtitle: "",
  },
  {
    id: 23,
    idProject: 12,
    url: "/images/fulminacci4.png",
    title: "",
    subtitle: "",
  },
  {
    id: 24,
    idProject: 13,
    url: "/images/peggy3.jpg",
    title: "",
    subtitle: "",
  },
  {
    id: 25,
    idProject: 13,
    url: "/images/peggy2.jpg",
    title: "",
    subtitle: "",
  },
];
