export const videoProjects = [
  {
    id: 1,
    idProject: 6,
    url: "⁠https://www.dropbox.com/scl/fi/a8f2rzz5v3v37wl68d3ck/FROSINONE_ROMA.mp4?rlkey=p28hvapygiuqpfwxyp6eib50w&st=7gov3nyr&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "ROMA",
  },
  {
    id: 2,
    idProject: 6,
    url: "⁠https://www.dropbox.com/scl/fi/20ywy2rqy11jg20mivevi/CALCUTTA_ROMA_01.mp4?rlkey=mq9d0rzya0sfv4r9rw5fsiggg&st=b09ismpq&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "ROMA",
  },
  {
    id: 3,
    idProject: 6,
    url: "⁠https://www.dropbox.com/scl/fi/rwjio5i4hoactp9byaquz/GAETANO.mp4?rlkey=gi45va5o0cqchzgh79zow5gg6&st=lr6mrypa&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "ALBA",
  },
  {
    id: 4,
    idProject: 7,
    url: "⁠https://www.dropbox.com/scl/fi/k8hrfv6azrpx2hauaz6rq/LIMONATA.mp4?rlkey=o4as9kp4u9do8y5rvhrhdn2sd&st=ocxfxol3&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "ALBA",
  },
  {
    id: 5,
    idProject: 7,
    url: "⁠https://www.dropbox.com/scl/fi/jxubh31osjh2nwf6abmkg/PESTO_LUCCA_2.mp4?rlkey=9og2h9018fch3i0b1taj1m5n5&st=ywspuj3u&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "LUCCA",
  },
  {
    id: 6,
    idProject: 7,
    url: "https://www.dropbox.com/scl/fi/fl4g2j9wtsfpkphk4xi2e/PESTO_LUCCA.mp4?rlkey=l1oxa28n6qgpe3gynl27vsk61&st=k57w9qsg&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "LUCCA",
  },
  {
    id: 7,
    idProject: 8,
    url: "⁠https://www.dropbox.com/scl/fi/gpub5zy2p5fpvlx1cz5vf/DUEMIN_LUCCA.mp4?rlkey=zjwbblphfj0oundhd5z0cttgc&st=sbjyj7jj&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "LUCCA",
  },
  {
    id: 7,
    idProject: 8,
    url: "⁠https://www.dropbox.com/scl/fi/zksb4dw8w630plejiqp7v/DEL-VERDE.mp4?rlkey=sv2cp3ybqgf40nbo7ri91znv9&st=bgrpit3v&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "LUCCA",
  },
  {
    id: 7,
    idProject: 8,
    url: "⁠https://www.dropbox.com/scl/fi/ne2xvm88sxh18zaztzcdn/DUEMIN_VILLAFRANCA.mp4?rlkey=fqlkjie4z6tlmva8uutnthewo&st=gcbg53mh&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "VILLAFRANCA",
  },
  {
    id: 7,
    idProject: 8,
    url: "⁠https://www.dropbox.com/scl/fi/sl57xls1l0sfhlvxonldy/FROSINONE_VILLAFRANCA.mp4?rlkey=b5y5r7uwkjs2oqtajshqb1uq9&st=t9nqoyfv&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "VILLAFRANCA",
  },
  {
    id: 7,
    idProject: 8,
    url: "⁠https://www.dropbox.com/scl/fi/2qcyin7pp1625ktg05pq3/ALLEGRIA_VILLAFRANCA.mp4?rlkey=xgyboeyjbd8ksba5vjudptywx&st=1xnzsqqm&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "VILLAFRANCA",
  },
  {
    id: 7,
    idProject: 8,
    url: "⁠https://www.dropbox.com/scl/fi/pr54wdh0l4zip2b7vg1jn/PARACETAMOLO_VILLAFRANCA.mp4?rlkey=3o6nmysw7kuu1uvf54e1fsjsc&st=biu77xtb&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "VILLAFRANCA",
  },
  {
    id: 7,
    idProject: 8,
    url: "⁠https://www.dropbox.com/scl/fi/zydq81yi6l7bvzt8xopxy/MILANO_GAETANO.mp4?rlkey=kbyi7mhxt3fu9j85xp6a3iw83&st=6fhrcfjh&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "MILANO",
  },
  {
    id: 7,
    idProject: 8,
    url: "⁠https://www.dropbox.com/scl/fi/q0aky3ewqvp00a5iegdzo/MILANO_HUBNER.mp4?rlkey=1e3ebwb5s7cwkm93gf8kzmnyw&st=670lhgtm&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "MILANO",
  },
  {
    id: 7,
    idProject: 8,
    url: "⁠https://www.dropbox.com/scl/fi/s7s4kti2a6iol05az0r6l/SORRISO_PAESTUM.mp4?rlkey=qgpc5wi2vzyl6aivgw19n5lp1&st=b93y7322&raw=1",
    title: "CALCUTTA SUMMER TOUR",
    subtitle: "PAESTUM",
  },
  {
    id: 8,
    idProject: 8,
    url: "https://drive.google.com/file/d/1aXbyesKiySruWTbS-36mDnLkDIrwpRrv/view?usp=drive_link",
    title: "RED VALLEY",
    subtitle: "DAY 1",
  },
  {
    id: 8,
    idProject: 8,
    url: "https://drive.google.com/drive/folders/1-7HeP5NbVUNJnxHlOepWA27er_c_PWN9",
    title: "RED VALLEY",
    subtitle: "DAY 2",
  },
  {
    id: 8,
    idProject: 8,
    url: "https://drive.google.com/file/d/1Prj7U-ykptnmoL1r7DmgaVcpMLi8AdId/view?usp=drive_link",
    title: "RED VALLEY",
    subtitle: "DAY 3",
  },
  {
    id: 8,
    idProject: 8,
    url: "https://drive.google.com/file/d/1dD17acnYFSPtcsSZbMWNeBS7ZqgGuRjU/view?usp=drive_link",
    title: "RED VALLEY",
    subtitle: "DAY 4",
  },

  {
    id: 8,
    idProject: 9,
    url: "/images/fulminacci1.png",
    title: "",
    subtitle: "",
  },
  {
    id: 9,
    idProject: 9,
    url: "/images/fulminacci2.png",
    alt: "Fulminacci",
  },
  {
    id: 10,
    idProject: 9,
    url: "/images/fulminacci3.png",
    title: "",
    subtitle: "",
  },
  {
    id: 11,
    idProject: 9,
    url: "/images/fulminacci4.png",
    title: "",
    subtitle: "",
  },
  {
    id: 12,
    idProject: 13,
    url: "/images/peggy3.jpg",
    title: "",
    subtitle: "",
  },
  {
    id: 13,
    idProject: 13,
    url: "/images/peggy2.jpg",
    title: "",
    subtitle: "",
  },
];
